"""remove_unique_from_username

Revision ID: 84668984feda
Revises: 6a73d4be0cf4
Create Date: 2026-05-31 14:57:56.618978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84668984feda'
down_revision: Union[str, Sequence[str], None] = '6a73d4be0cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_name'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('user_name'), 'users', ['user_name'], unique=True)
    # ### end Alembic commands ###
