name: Run Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Установка репозитария
        uses: actions/checkout@v4

      - name: Установка пайтон
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установка библиотек
        run: pip install -r requirements.txt

      - name: Pytest тесты
        run: pytest -v