name: Run Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Gersolo2009.
          MYSQL_DATABASE: ai_news_bot
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Wait for MySQL
        run: sleep 20
      - run: pytest -v
        env:
          database_url: "mysql+aiomysql://root:Gersolo2009.@127.0.0.1:3306/ai_news_bot"

